// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mfkujcmkrowdqqsyfnfs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ma3VqY21rcm93ZHFxc3lmbmZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwNjQxMjAsImV4cCI6MjA2OTY0MDEyMH0.QztnotRJuI2MocNoM6iRglYhoADhPSU_3own9JX0hzo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});